# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    tighten_type_of_initializing_formals: true
    use_build_context_synchronously: true
    avoid_dynamic_calls: true
    prefer_final_locals: true
    unawaited_futures: true
    unnecessary_late: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
